### ISSUE TITLE
Support data-* attributes

### ISSUE THREAD

**Issue by jessehattabaugh** [react-component/drawer#107]
I am using antd.Drawer and I am trying to add a data-* attribute to it like so:

```
<Drawer data-test-id="something">...
```

Unfortunately that attribute doesn't get reflected in the DOM so my automated tests aren't able to locate the element. 

Other attrs like aria-* would probably also be appreciated.

**Comment by jljsj33** [comment]
:ok_hand:

**Comment by jessehattabaugh** [comment]
🙌 thanks!!

**Comment by jljsj33** [comment]
v1.10.0

**Comment by haggen** [comment]
I think the latest major release broke this feature. Any plans to support it again?

**Comment by jljsj33** [comment]
@zombieJ

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/issues/286
