### ISSUE TITLE
Unknown Prop Warning

### ISSUE THREAD

**Issue by Symboler** [react-component/drawer#109]
on version1.10.1，you use  {...props}  in the Drawer.js，its easy to resulted warning  “warning: React does not recognize the xxx prop on a DOM element ” when i pass some other props to the component,so could you make a change  to it ?
![image](https://user-images.githubusercontent.com/33592051/60391972-f43cc380-9b2c-11e9-9825-a800c1dc98c5.png)

**Comment by jljsj33** [comment]
在 `<Drawer />` 上除了加 `props` 和 `HTMLAttributes` 的属性，，你还需要加什么属性？？
