### ISSUE TITLE
Click outside to close Drawer when set mask equal false

### ISSUE THREAD

**Issue by zquancai** [react-component/drawer#111]
like this.
<img width="1112" alt="Screenshot 2019-07-09 at 6 06 08 PM" src="https://user-images.githubusercontent.com/8609783/60879578-76875f00-a274-11e9-8f3e-7c169ea42c3f.png">

this feature maybe like component popover.

**Comment by jljsj33** [comment]
这样的需求直接设置 mask 的 opacity 为 0 就可以了，不需要把 mask 设为 false

**Comment by zquancai** [comment]
你没理解我的意思。
我的意思是点击左侧时，右侧会收起来，并且左侧点击部位（比如是个按钮）会被触发事件，而不是点击了 mask 遮罩。
效果类似于 popover，实现代码可以参照 popover 实现。

**Comment by zquancai** [comment]
@jljsj33 
> 这样的需求直接设置 mask 的 opacity 为 0 就可以了，不需要把 mask 设为 false

你没理解我的意思。
我的意思是点击左侧时，右侧会收起来，并且左侧点击部位（比如是个按钮）会被触发事件，而不是点击了 mask 遮罩。
效果类似于 popover，实现代码可以参照 popover 实现。

**Comment by jljsj33** [comment]
onBlur 了就关闭？？？感觉不是很有必要，抽屉本来就有 mask 层事件，，如果没有 mask，点击的是按钮，，直接在抽屉组件上加 onBlur 或在按钮上控制就行了。。。

**Comment by zquancai** [comment]
> onBlur 了就关闭？？？感觉不是很有必要，抽屉本来就有 mask 层事件，，如果没有 mask，点击的是按钮，，直接在抽屉组件上加 onBlur 或在按钮上控制就行了。。。

antd 的抽屉组件哪里来的 onBlur 事件，按钮只是一个例子，需要的是点击 outside 时，会收起抽屉，并且 focus 到点击的元素上。参照钉钉客户端的“群设置”抽屉交互？要不我提个 pr 吧。。。

**Comment by jljsj33** [comment]
[![Edit Drawer default menu](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawer-default-menu-stbyj?fontsize=14)

onBlur 不是组件的 API,,, 是 dom 的 API。。。组件虽好用，但也别忘了原生的东西...

**Comment by zquancai** [comment]
> [![Edit Drawer default menu](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/drawer-default-menu-stbyj?fontsize=14)
> 
> onBlur 不是组件的 API,,, 是 dom 的 API。。。组件虽好用，但也别忘了原生的东西...

你说得对，但我就是没忘才问，因为这样写明显有 bug，请看这里 https://codesandbox.io/s/drawer-default-menu-4otd3

此外，onBlur 会在失去焦点时触发，如果有 focus 一个元素，点击地址栏也会触发 onBlur 事件。
https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event

有上面两个问题，显然不符合组件交互逻辑

PS，React 的事件和原生事件异口同声：我们不一样。。。

**Comment by jljsj33** [comment]
大哥别杠了，可能前面我对你的需求没想周全，，如果不满足你的需求，，你可以在 DidMount 后给 document 加个事件，这种额外的功能可以自行解决。。。

```jsx
function contains(root, n) {
  let node = n;
  while (node) {
    if (node === root) {
      return true;
    }
    node = node.parentNode;
  }
  return false;
}

onDocumentClick = (e) => {
  if (!contains(root, e.target)) {
     // close drawer
  }
}
```

[![Edit Drawer default menu](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawer-default-menu-gis86?fontsize=14)

**Comment by zquancai** [comment]
> 大哥别杠了，可能前面我对你的需求没想周全，，如果不满足你的需求，，你可以在 DidMount 后给 document 加个事件，这种额外的功能可以自行解决。。。
> 
> ```js-jsx
> function contains(root, n) {
>   let node = n;
>   while (node) {
>     if (node === root) {
>       return true;
>     }
>     node = node.parentNode;
>   }
>   return false;
> }
> 
> onDocumentClick = (e) => {
>   if (!contains(root, e.target)) {
>      // close drawer
>   }
> }
> ```
> 
> [![Edit Drawer default menu](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/drawer-default-menu-gis86?fontsize=14)


我从一开始就是这个想法（popover），你一直忽视而已。既然 drawer 组件不打算增加这个功能，那我就自己加呗。
你也有意思。。。讨论问题说我杠。。

**Comment by jljsj33** [comment]
哈哈，，好了，，我的错。。。额外功能能自行解决就自行解决吧。。。这种加到内部里需要考虑很多问题，，，而且抽屉一般有 mask 存在，，，这两功能是重复的。。。

**Comment by zquancai** [comment]
我觉得两种交互不冲突吧

第一种交互是：drawer 内容具有有强交互属性，比如表单，为了防止其他具有副作用的操作（或者干扰，或者用户做了其他，导致表），mask 可以和 modal 组件保持一样

第二种交互是：这仅仅是个提示（查看的内容），或者应用并不关心用户对 drawer 的操作，只要用户去做其他事了，drawer 自动收起。而不需要先点击 mask 再收起，或者要点击X才收起。
第二种交互可以参照，mac 里的 Notification Centre 抽屉交互，以及钉钉 APP 里的“群设置”抽屉交互

yy 一把场景

**Comment by jljsj33** [comment]
感觉不是很靠谱，我目前能想到的就有几种可能和问题，

- 按你第一种逻辑，mask 存在的情况不需要此功能。 
- 需要增加 API 来可选使用此功能。
- antd 二级抽屉，二级打开的时候，点到二级时，一级会不会回收，在一级上操作时，二级会不会回收，，目前按你这个需求是肯定会收回的。
- level 里的推开抽屉，跟 3 相似。。

最大问题还是多层级抽屉，，二层出来后肯定会把一层收回。。。

**Comment by zquancai** [comment]
嗯嗯，这个多级抽屉还没看 drwer 怎么实现的
但是假设一下，如果多级抽屉都在一个容器里，那么这个二层出来后第一层收回的诡异逻辑就不会有了。

而且我这个逻辑加上去的话，也会有副作用的，比如，在 drawer 里弹出了一个 modal，用户在 modal 里操作时，drawer 也会收起，除非将 modal 的父容器设为 drawer 所在的容器。

我先自个儿实现呗，这个功能后续需求多的话可以考虑加上吧。谢谢解答~~
