### ISSUE TITLE
是否可以考虑增加初始时，dom不加载？

### ISSUE THREAD

**Issue by Frank1e0927** [react-component/drawer#13]
现状：看了一下源码，似乎只要在业务代码中中增加了Drawer，就一定会在初始化的时候加载了Drawer通过protal生成的DOM节点
期待：(在没有按钮的外置情况下)，希望能够提供默认初始化不生成DOM节点的能力，类似于Modal。

**Comment by jljsj33** [comment]
modal 是还有附加元素的，，所以开始时没有 dom ，，触发后才会有，，但 drawer 是有额外元素的（自带的 icon 按钮）, 所以需要默认渲染。。。

**Comment by Frank1e0927** [comment]
Drawer的额外元素，我看到handleChild也可以不传啊。

handleChild | boolean / ReactElement | true | true or false or ReactElement

不能走两个判断？假设有handleChild，那么就走初始化DOM，没有，就不走初始化DOM。
譬如有一个table，需求是点击的时候展示Drawer，但是也有用户会不点击光看列表，那么这个Drawer在document当中就是冗余的。

**Comment by jljsj33** [comment]
🆗

**Comment by jljsj33** [comment]
1.4.0
