### ISSUE TITLE
place the handler

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#15]
i can not place the handler an the menu. when i  do it it hidden from screen

**Comment by jljsj33** [comment]
Please provide your detailed demo. https://codesandbox.io/s/yp5y3lww89

**Comment by romanown** [comment]
thank You for test place. for mobile when opened the handler need into his rectangle.
https://codesandbox.io/s/z6l2zlxvp

**Comment by romanown** [comment]
full example https://codesandbox.io/s/zkj18410np

**Comment by romanown** [comment]
mobile screen realy 320px, when driver opened to full screen handler is not take or opened not ful screen

**Comment by jljsj33** [comment]
https://codesandbox.io/s/m3kljkmzlj

**Comment by romanown** [comment]
no. handler need in this place there i put [X]

**Comment by romanown** [comment]
https://codesandbox.io/s/oxyz3wv045

**Comment by romanown** [comment]
when the menu is opened the item to close is moved to the menu itself up on the right. otherwise, the menu does not open the entire width of the screen leaving space for the closing element.

**Comment by jljsj33** [comment]
Please look at API carefully

**Comment by romanown** [comment]
i can not view need props

**Comment by jljsj33** [comment]
https://codesandbox.io/s/ov1lpp43m6

**Comment by romanown** [comment]
haw i can close driver?

**Comment by romanown** [comment]
handler need into menu

**Comment by romanown** [comment]
if onOpen Handle go to left

**Comment by jljsj33** [comment]
```css
.drawer-open .drawer-handle {
  right: 0;
}

```

**Comment by jljsj33** [comment]
Stackoverflow would be a better place for such problem.

**Comment by romanown** [comment]
but this is an intervention in the module. it is more convenient to do this by module props

**Comment by romanown** [comment]
i am added this kode into css/ it is working/ thank You. to better way for me if to do this by module props

**Comment by romanown** [comment]
i am tried  <Drawer style={{
          'drawerHandle': {
            zIndex: 1,
          },
          'drawerOpen & drawerHandle': {
  right: 0,
  top:0,
 },
  width: "100%" }}
  >
not taked effect
https://codesandbox.io/s/9y326wkmko

**Comment by jljsj33** [comment]
https://codesandbox.io/s/ov1lpp43m6

**Comment by romanown** [comment]
thank You. for the finished module a lot of code added. it is more convenient to do this props of module

**Comment by romanown** [comment]
i am using the
 .drawer-open .drawer-handle {
  right: 0;
}
it is working
thank You

**Comment by jljsj33** [comment]
```css
.drawer-handle {
  transition: right 0.3s;
  z-index: 1;
}
.drawer-open .drawer-handle {
  right: 0;
}

```

**Comment by romanown** [comment]
thank You

**Comment by romanown** [comment]
see please http://dev.thedressfor.ru/catalog/

**Comment by romanown** [comment]
<Drawer style={{width: '100%'}}> 
and in the index.css
.drawer-left .drawer-content-wrapper,
.drawer-right .drawer-content-wrapper,
.drawer-left .drawer-content,
.drawer-right .drawer-content {
  height: 100%;
  width: 100%;
}

**Comment by romanown** [comment]
when open and close the drawer the handler is half to left

**Comment by jljsj33** [comment]
width: 50vw

**Comment by jljsj33** [comment]
Just change the width of your children.
```jsx
<Menu style={{ width: '50vw' }}>
</Menu>
```

**Comment by romanown** [comment]
Not true. initially, the handler is located correctly but when I click on the handler to open the menu and then click to close it moves to the left. this link shows it. and part of it is not visible behind the left edge.

**Comment by romanown** [comment]
thank You very match. You  the best.  the reason was the menu option alignContent: 'center'

**Comment by romanown** [comment]
thank You very match. You the best. 
https://codesandbox.io/s/o76oqwz1xq
that's what I wanted. but when you resize the output window, the handler shifts. after the page is refreshed, it returns to its place.
