### ISSUE TITLE
can i slide only drawer?

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#17]
can it as http://negomi.github.io/react-burger-menu/  with mode Slide ?

**Comment by romanown** [comment]
it have same useful the props. but You componrents is better.

**Comment by jljsj33** [comment]
Please read API and demo carefully.

**Comment by jljsj33** [comment]
https://react-component.github.io/drawer/examples/level.html

**Comment by romanown** [comment]
thank You. that's what i need. many props are not described in detail in the API description for those who are not familiar with this module.
