### ISSUE TITLE
页面 html, body 设置滚动条隐藏的时候会出现白边

### ISSUE THREAD

**Issue by nuintun** [react-component/drawer#20]
[L260](https://github.com/react-component/drawer/blob/1.5.0/src/Drawer.js#L260)

如题，隐藏 `html, body` 滚动条的情况下由于计算了滚动条宽度，右侧会出现白边，最好能加个选项设置是否忽略滚动条，默认设置计算滚动条。

![_20180702102446](https://user-images.githubusercontent.com/1730277/42142520-74c8cf8a-7de2-11e8-9e0e-bfa44beec5de.png)

另外在组件 `componentWillUnmount` 时候没有还原 `body` 宽度！

![_20180702102803](https://user-images.githubusercontent.com/1730277/42142562-a5d89506-7de2-11e8-9106-93f1441d2602.png)

**Comment by jljsj33** [comment]
右侧留白没什么大问题吧，，没关系的吧。。有 mask 背景遮住，不会有人注意的。。。。

**Comment by jljsj33** [comment]
componentWillUnmount 没还原？？？我看看，，不科学啊，，，

**Comment by nuintun** [comment]
@jljsj33 二图是 `Unmount` 后的截图

**Comment by jljsj33** [comment]
1.5.2

**Comment by Gong-Elory** [comment]
这个问题我也出现了 导致现在无法正常使用该组件
