### ISSUE TITLE
position relative of the button to open and close (the handler)

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#22]
https://codesandbox.io/s/9z3zrz3814 I can not put the handler that it is always located on the 1/3 of the window width when you change the window width when the menu is closed

**Comment by jljsj33** [comment]
https://react-component.github.io/drawer/examples/change.html

**Comment by romanown** [comment]
I need when window is changing the his of width, the drawer handler place on 1/3 from left border.
but in the this example `handler={false}`
> https://react-component.github.io/drawer/examples/change.html
>

**Comment by romanown** [comment]
in all the examples, the handler is located at the edge of the window. but if it is located at some distance from the edge as in my example, it is impossible that this distance changes proportionally to the width of the document or browser window even if I make `left:30%`.

**Comment by jljsj33** [comment]
If you can, please provide the following diagram, I really don't understand what you mean.

**Comment by romanown** [comment]
https://codesandbox.io/s/9z3zrz3814 
in this example, the handler is located 1/5 of the edge of the window at a width of 900. when I reduce the width of the window to 300 it is already in the middle. and I have to, he was always in the 1/5 from the edge depending on the width of the window or another distance that I specify. but be sure to change the window width proportionally and the distance from the edge to this element.

**Comment by jljsj33** [comment]
。。。。。
You can try setting `handler` to false and then adding a button to the body to control the drawer switch. The button `left` is set to `20vw`...

**Comment by jljsj33** [comment]
or
```css
.drawer-handle {
    right: -20vw
}
```

**Comment by romanown** [comment]
thank You. the module has a control element. why add new items? of course it's good to have this opportunity.
