### ISSUE TITLE
change the appearance of the button to open and close (the handler)

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#23]
how to change the appearance of the open and close button (the handler) of the drawer?

**Comment by jljsj33** [comment]
Please go to understand the `less`.

**Comment by romanown** [comment]
I need do it through the props of the drawer, for example, convey a style. 
`<Drawer style={{ handlerOpen:{color:'#678,width: 20}, handlerClose: {color:'#123} }} />`

**Comment by jljsj33** [comment]
We will not do this, and we can replace it with `less`.

### close
https://github.com/react-component/drawer/blob/master/assets/index.less#L31 
### open
https://github.com/react-component/drawer/blob/master/assets/index.less#L161

**Comment by romanown** [comment]
thanks for the detailed description. I understand that. I did exactly as you wrote. but it is very inconvenient to change the internal structure of the module. it is much more convenient to pass all this parameters and properties. on one page you need some parameters and on the other you may need others. or do you need to install several components and change them?

**Comment by romanown** [comment]
can i use in the drawer-handle-icon not the css transform but also the image_open.png and image_close.png?

**Comment by jljsj33** [comment]
handler | boolean \| ReactElement | true | true or false or ReactElement, default:<divclassName="drawer-handle"><i className="drawer-handle-icon" /></div>;
-- | -- | -- | --

**Comment by romanown** [comment]
give example plese. i am do not understand as do it.

**Comment by romanown** [comment]
I do not want to replace the item but instead its 3 strips and cross put a picture but use the built-in the handler

**Comment by romanown** [comment]
I want to make on a light background shows a dark picture and a dark light and also change the picture depending on the page. this will make the drawer more versatile and allow you to use it for different tasks.

**Comment by jljsj33** [comment]
```jsx
class Demo extends React.Component {
  state = {
    open: false,
  }
  onChange = (open) => {
    this.setState({
      open
    })
  }
  render() {
    return (
      <Drawer onChange={this.onChange} handler={<div><img src={this.state.open ? 'image_open.png' : 'image_close.png'} /></div>} />
    );
  }
}
```

**Comment by romanown** [comment]
thank You very match.

**Comment by romanown** [comment]
it will be more convenient if you add the opened property to the drawer. then don't write so much. example 
`handler={<div><img src={drawer.opened ? 'image_open.png' : 'image_close.png'}`

**Comment by romanown** [comment]
it is necessary to change the color of the elements of the handler depending on what page is the menu. but do not use the state yourself as in the example above. you also need the property to know whether the drawer is open or closed without using the state.

**Comment by romanown** [comment]
on the website the main page is dark and the rest are light. I need to make this element light on the front page and dark on the other pages. as well as the border around the element when the driwer is opened and to remove the curb when the driwer is closed.
