### ISSUE TITLE
Add dimension prop

### ISSUE THREAD

**Issue by yesmeck** [react-component/drawer#24]
For width/height of `.ant-drawer-content-wrapper`.

https://github.com/ant-design/ant-design/issues/11298

**Comment by jljsj33** [comment]
底层没有宽度控制的。。。children 有多宽就多宽的。。。他可以用 vw 来控制 % 。。。因为他这 % 就相当于窗口的宽度。。。

**Comment by jljsj33** [comment]
哦，，陈帅在 antd 里包了个 width。。。。

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/blob/master/components/drawer/index.tsx#L155-L157

这个没啥卵用。。写错地方了吧。。 @chenshuai2144 

https://github.com/ant-design/ant-design/blob/master/components/drawer/index.tsx#L110 
写在这吧。。。。

**Comment by chenshuai2144** [comment]
等我找个时间重新搞一搞

**Comment by chenshuai2144** [comment]
@jljsj33  你可以dimension 加个这个props 这样我的工作量就小了

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/11298 已经关了的话就这样吧。

**Comment by yesmeck** [comment]
不用再加了。
