### ISSUE TITLE
Conflict with another package

### ISSUE THREAD

**Issue by Victordmdb** [react-component/drawer#25]
This is rather specific but it might also impact other packages. I haven't yet figured out the source of the issue but the core of it is related to having a [react tags ](https://github.com/prakhar1989/react-tags) element within an rc-drawer.

The drawer will not load the css transitions, and therefore it will be rendered next to the drawer content.

I'll try to figure out where the issue is coming from.

**Comment by jljsj33** [comment]
Please provide demo. https://codesandbox.io/s/ww0r05ry7

**Comment by Victordmdb** [comment]
Sorry, I realise that the issue is actually with a similarly name package: https://github.com/react-component/m-drawer (which was renamed from rc-drawer recently)
