### ISSUE TITLE
Can't unmount Drawer

### ISSUE THREAD

**Issue by luisgurmendez** [react-component/drawer#28]
I've recently start using the Drawer component, and coulnd't be able to unmount it. When ever I try there's an error:

Uncaught (in promise) TypeError: this.renderComponent is not a function
    at Drawer.componentWillUnmount (Drawer.js:114)
    at ReactCompositeComponent.js:406
    at measureLifeCyclePerf (ReactCompositeComponent.js:73)
    at ReactCompositeComponentWrapper.unmountComponent (ReactCompositeComponent.js:405)
    at Object.unmountComponent (ReactReconciler.js:76)
    at Object.unmountChildren (ReactChildReconciler.js:144)
    at ReactDOMComponent.unmountChildren (ReactMultiChild.js:369)
    at ReactDOMComponent.unmountComponent (ReactDOMComponent.js:992)
    at Object.unmountComponent (ReactReconciler.js:76)
    at ReactCompositeComponentWrapper.unmountComponent (ReactCompositeComponent.js:415)

I have been trying to reproduce the error in jsfiddle or something, but I'm pretty new to React and could find a way to do this. If someone could help with reproducing the error, that would be great, and also, how to fix it :).

I import the rc-drawer directly and don't use antd.Drawer because I'm usnig previous version of antd.

I'm using versions: 
    "rc-drawer": "^1.6.2",
    "react": "^15.6.1",
    "antd": "2.13.11",

**Comment by luisgurmendez** [comment]
For now I comment the following lines in lib/Drawer.js :
```
/*
this.renderComponent({
      afterClose: this.removeContainer,
      onClose() { },
      visible: false,
    });
*/
```

**Comment by jljsj33** [comment]
No problem. https://codesandbox.io/s/w647rn1y68

**Comment by luisgurmendez** [comment]
You are right, there seems to be a problem but not with this library. I will keep trying to see whats going on. 

I think I have found the problem thou, I have debugged the render function and found that after line [L506](https://github.com/react-component/drawer/blob/master/src/Drawer.js#L506) the `renderComponent` function is not saved in `this` . The screenshot below show whats happening.

<img width="631" alt="captura de pantalla 2018-07-31 a la s 14 38 35" src="https://user-images.githubusercontent.com/17949470/43476700-9acc94d8-94cf-11e8-8bff-11261d12f1f5.png">

The this object is not the Drawer object is this expected? I've change line [L506](https://github.com/react-component/drawer/blob/master/src/Drawer.js#L506)

to `this.parent.renderComponent = renderComponent` but didn't fix my issue

In line [L134](https://github.com/react-component/drawer/blob/master/src/Drawer.js#L134) I have:

<img width="578" alt="captura de pantalla 2018-07-31 a la s 14 51 28" src="https://user-images.githubusercontent.com/17949470/43477402-7c559fd4-94d1-11e8-8054-5d63b9ddd4bf.png">

I don't think that that is expected. Do you have a clue of what could be going on? (I'm using 2 drawers, but I don't think that that is relevant)

**Comment by jljsj33** [comment]
Can you reproduce it in the demo I offer? Otherwise I can't locate the problem.

**Comment by allenwbw** [comment]
I ran into the same problem. Hacked it by changing [L114](https://github.com/react-component/drawer/blob/master/src/Drawer.js#L114) to `this.render({`

**Comment by jljsj33** [comment]
L114 ？？？？？？？

**Comment by chenshuai2144** [comment]
我记得我已经改掉了，增加了判断

**Comment by luisgurmendez** [comment]
@jljsj33 I think he mean [Line 134](https://github.com/react-component/drawer/blob/master/src/Drawer.js#L134)

**Comment by luisgurmendez** [comment]
@allenwbw  Your solution solved my issue :)

**Comment by allenwbw** [comment]
I am using react 15.6.1. I noticed the version checking on [L131](https://github.com/react-component/drawer/blob/master/src/Drawer.js#L131). I guess 15.6.1 doesn't support `renderComponent()` but the version checking does not account for that.

Checked react's changelog, turns out `renderComponent()` is deprecated since react v0.12.0 and changed to `render()`. Maybe this is the issue?

**Comment by jljsj33** [comment]
https://github.com/react-component/util/blob/master/src/ContainerRender.js#L49 `rc-util` It's also used `renderComponent`

@yesmeck

**Comment by yesmeck** [comment]
@allenwbw  Could you reproduce your issue on https://codesandbox.io?

**Comment by allenwbw** [comment]
@jljsj33 @yesmeck I used the Drawer component from antd@3.7.3(together with react@15.6.1) which is the version where I ran into the problem. The bug happens when the drawer component gets unmounted. I rendered the drawer first and set a timeout to unmount the component. You can see the error after 10 seconds.
`render(<Demo />, document.getElementById("root"));`
`setTimeout(() => {unmountComponentAtNode(document.getElementById("root"));}, 100000);`
https://codesandbox.io/s/x7p1pn3pno

**Comment by yesmeck** [comment]
@jljsj33 unmount 里判断下 this.renderComponent 是不是存在

**Comment by jljsj33** [comment]
~@yesmeck 这不是判断的问题。。。是 handler 的值变了。~

好吧，，我看错了，，竟然用的是 antd 的...

**Comment by jljsj33** [comment]
v1.6.3

**Comment by luisgurmendez** [comment]
Thanks @allenwbw for reproducing the error! I couldnt do it!. And also thanks team for the rapid response and for solving it!
