### ISSUE TITLE
Can't set data-testid on drawer

### ISSUE THREAD

**Issue by gtb104** [react-component/drawer#286]
After version `4.4.3`, we've lost the ability to set the `data-testid` attribute on Drawer.

**Comment by nzkn** [comment]
I am facing the same issue. Version `4.23.2`

**Comment by rkuykendall** [comment]
Same issue, version `antd@5.2.1` `rc-drawer@6.1.1`

**Comment by rkuykendall** [comment]
I think this PR is a fix but I'm having trouble testing locally. I can confirm it passes tests locally.

https://github.com/react-component/drawer/pull/404

**Comment by rkuykendall** [comment]
I can confirm my fix is in. This issue can be closed.

**Comment by rkuykendall** [comment]
@gtb104
