### ISSUE TITLE
The new API `handleChild` may have wrong propTypes check.

### ISSUE THREAD

**Issue by jbiter** [react-component/drawer#3]
I've upgraded `rc-drawer-menu` (0.5.7 => 1.0.1) in my project and changed its props to adapt to the new API

```javascript
<DrawerMenu
  level={null}
  handleChild={false}
  open={!props.collapsed}
  getContainer={null}
  onMaskClick={() => {
    props.onCollapse(true);
  }}
>
  <SiderMenu {...props} />
</DrawerMenu>
```
It gives me a warning like this:
![image](https://user-images.githubusercontent.com/16318438/40293192-52b72c58-5d02-11e8-936f-aec1a4720353.png)

It seems like `handleChild` supports a boolean value in API doc. 

Then I found Drawer.propTypes config in `rc-drawer-menu/lib/Drawer.js`

```javascript
Drawer.propTypes = {
 // only element
  handleChild: _propTypes2['default'].element,
};
```
I wonder if it caused this warning.

**Comment by jljsj33** [comment]
yes, thx...1.0.2
