### ISSUE TITLE
prefix this does not affect to the handler

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#31]
if I set the prefix this does not affect to the handler, example prefixCls='mydrawer' 
![drawer_prefix](https://user-images.githubusercontent.com/7169357/43983972-347eddbe-9d06-11e8-8e6d-5e21914512a0.jpg). it is right? maybe that's what it's meant to be?
https://codesandbox.io/s/ykq7rlzmz9

**Comment by romanown** [comment]
when I did prefixCls={isMain ? 'drawermy' : 'drawer'}, I copied the old css file. I called a copy of indexmy.css renamed it ' .drawer {' in '.drawermy {' and so in the whole file hooked it up in the index.js as writed an stackoverflow the drawer has stopped showing at all.

**Comment by romanown** [comment]
and if `prefixCls='mydrawer'` is `.drawer-open .drawer-handle` not working. it is not changing to `.mydrawer-open .mydrawer-handle` when drawer is opened.

**Comment by romanown** [comment]
I did find how to change the code of the component to parameter prefixCls effect on the "Burger". I took as a basis the default code of this element and added prefixCls. Maybe I did it wrong so the code doesn't show up to not distort your thoughts.

**Comment by romanown** [comment]
But if you do not have time and desire to do this here is the code to control and add to the component.
`var _props3 = _this3.props,
        className = _props3.className,
        prefixCls = _props3.prefixCls,
        style = _props3.style,
        placement = _props3.placement,
        children = _props3.children,`
the beginning of change
       ` handler = React.createElement(
    'div',
    { className: prefixCls + '-handle' },
    React.createElement('i', { className: prefixCls + '-handle-icon' })
  ),`
the ending of change
     `  showMask = _props3.showMask,
        maskStyle = _props3.maskStyle;`

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/issues/37

**Comment by romanown** [comment]
But the issue 37 describes another problem. 37 issue describes is no action and this does not change the appearance of the item
