### ISSUE TITLE
安卓微信内置浏览器内无效

### ISSUE THREAD

**Issue by yuuk** [react-component/drawer#331]
安卓微信内置浏览器访问demo地址，点击 “打开” 按钮无任何反应，ios 微信内置浏览器正常

https://drawer-react-component.vercel.app/demo/base

**Comment by yuuk** [comment]
调试发现是css样式问题，inset: 0; 兼容问题

**Comment by yoyo837** [comment]
我个人讨厌死了这个X5内核.

**Comment by yoyo837** [comment]
就好比这个 https://caniuse.com/?search=rrggbbaa, `Chrome` 62就支持了, `X5`的`Chromium`是89也不支持. `Browserslist`被迫配置为 61 .

**Comment by yuuk** [comment]
https://github.com/react-component/drawer/pull/345
