### ISSUE TITLE
if prefixCls is set do not drawer-handle to drawer-handle drawer-open

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#34]
if I did `prefixCls='mydrawer'` then the class of the handler does not change from `drawer-handle` to `drawer-handle drawer-open` when you open the drawer and strips do not become cross.

**Comment by romanown** [comment]
I did find how to change the code of the component to parameter prefixCls effect on the "Burger". I took as a basis the default code of this element and added prefixCls. Maybe I did it wrong so the code doesn't show up to not distort your thoughts.

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/issues/37
