### ISSUE TITLE
Width calculation is wrong when opening the drawer

### ISSUE THREAD

**Issue by datoml** [react-component/drawer#36]
Hello,
I changed from rc-drawer-menu to rc-drawer and it seems that the calculation for the body width is wrong.
It always subtracts the scrollbar width, even when there's no scrollbar visible. In my case, the page has a 17px space on the right when opening the sidebar.

**Comment by jljsj33** [comment]
please provide your demo， https://codesandbox.io/s/3xpp3mlp45

**Comment by datoml** [comment]
Hello @jljsj33!
Here's the example to reproduce it.
[https://codesandbox.io/s/k06rm3p235](https://codesandbox.io/s/k06rm3p235)

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/44265900-143bff00-a25b-11e8-93d2-cba638901821.png)

There seems to be no problem on my side.

**Comment by datoml** [comment]
Here's the proof. I am using the latest version of chrome.
![image](https://user-images.githubusercontent.com/10552487/44272585-94536c00-a23d-11e8-9759-d166280bd286.png)

**Comment by heineiuo** [comment]
@jljsj33 

https://github.com/react-component/drawer/blob/0abc35795ab06ebb985f2a03aadc7eb33b93a778/src/Drawer.js#L247

`getScrollBarSize` always return the scrollbar size of your browser, instead of `body` element.  `0` on macOS and `17` on Windows (chrome)

**Comment by jljsj33** [comment]
@chenshuai2144 合下发个版本。。。。
