### ISSUE TITLE
TypeError: e.dom is undefined

### ISSUE THREAD

**Issue by romanown** [react-component/drawer#39]
periodically, when navigating between pages, a white blank field appears instead of the page content and an error occurs 
`TypeError: e.dom is undefined Drawer.js:358 
k/this.setLevelDomTransform Drawer.js:358
O</t.prototype.componentWillUnmount Drawer.js:106'

![default](https://user-images.githubusercontent.com/7169357/44755327-60762180-ab2e-11e8-8f02-90edc5647be5.png)
before using the drawer and after the shutdown, this did not happen

string 358 of the Drawer.js is
` _this3.dom.style.transition = 'none';`

in my app
`<Drawer level = 'null' prefixCls={isMain ? 'mydrawer' : 'drawer'}  >`

**Comment by jljsj33** [comment]
level={null}

**Comment by romanown** [comment]
without results. also a mistake.
![default](https://user-images.githubusercontent.com/7169357/44770151-c1721980-ab6f-11e8-8dce-2cae079d0ad3.png)
even have to remove all the options (`<Drawer >`) when you click back in the browser an error occurs. sometimes first back then the link click and then an error occurs

**Comment by romanown** [comment]
I deleted the Drawer and used the links and back button in the browser the error stopped appearing.

**Comment by romanown** [comment]
Will there be a solution to this problem? You closed issue but there is no solution. the settings you specified did not correct the situation.

**Comment by jljsj33** [comment]
Can you provide demo?

**Comment by romanown** [comment]
I redid the code and removed the drawer. I won't be able to show all the code but I'll try to add up a significant part and lay out. I want to do it privately.

**Comment by jljsj33** [comment]
oh, Thx

**Comment by romanown** [comment]
```
const Nmenu = withRouter(observer(injectSheet({
  menu: {
    marginTop: 5,
    zIndex: 1000,
    justifyContent: 'space-around',
    flexWrap: 'wrap',
	background: '#a1c0be',
	width: '90%',
  textAlign: 'center',
  color: 'white', 	
  },
 })(
  class extends React.Component {
    render() {
		const {classes} = this.props;
    return (
            <div className={classes.menu}>
				 <Drawer level = 'null' 	prefixCls={isMain ? 'mydrawer' : 'drawer'}	 >
		 <Menu
	style={{backgroundColor: '#2e8982cc', textAlign: 'center', color: '#dedede',  paddingLeft: '3px', paddingTop: '0px', width: '100vw', maxWidth: '360px'}}
	mode= 'inline'
	inlineIndent ='0'   >
<MenuItem key='001'>qw</MenuItem>
      <SubMenu title={titlesRight[0]} key="1">...
```
