### ISSUE TITLE
Package.json - wrong licence definition

### ISSUE THREAD

**Issue by ondrejzemanek** [react-component/drawer#411]
Hello, 

we are having issues with package config as it contains a typo in package.json:
"**licenses**": "MIT" instead of "**license**": "MIT".  

It would be very helpful if you can fix it, as we have to ask for approval from our security/license department each time a new version of rc-drawer is released.

You can see that even npmjs.com site is not recognizing the MIT licence: https://www.npmjs.com/package/rc-drawer and same for our auto-license checker.

See for example rc-picker [package.json file](https://github.com/gem-mine/rc-picker/blob/master/package.json) for reference.

Thank you!

**Comment by afc163** [comment]
https://github.com/react-component/drawer/pull/416
