### ISSUE TITLE
Bug: panelRef 似乎获取不到 dom 元素

### ISSUE THREAD

**Issue by lixiao1022** [react-component/drawer#429]
https://codesandbox.io/s/ji-chu-chou-ti-antd-5-9-4-forked-82h8yh?file=/demo.tsx:624-632

**Comment by yoyo837** [comment]
Breaking by https://github.com/ant-design/ant-design/pull/44104

**Comment by yoyo837** [comment]
`panelRef` 在 `antd` 似乎是非公开的内部API, 没有写到文档里的, 应尽量避免使用, 该问题等核心成员意见看看如何处理.

**Comment by lixiao1022** [comment]
好的

**Comment by zombieJ** [comment]
rc 里的接口没透到 antd 文档基本都是给 antd 内部用的：
* [FAQ: 官方文档中没有提供的隐藏-api-我可以使用吗](https://ant-design.antgroup.com/docs/react/faq-cn#%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%AD%E6%B2%A1%E6%9C%89%E6%8F%90%E4%BE%9B%E7%9A%84%E9%9A%90%E8%97%8F-api-%E6%88%91%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%90%97)

**Comment by yoyo837** [comment]
这个FAQ我还真没注意到.

So, 这个就先关闭了.

**Comment by lixiao1022** [comment]
> 这个FAQ我还真没注意到.
> 
> So, 这个就先关闭了.

没关系，只是发现了一个 bug，提一下。我并不使用这个 api
