### ISSUE TITLE
Get rid of the scrollbar at the bottom?

### ISSUE THREAD

**Issue by demonoidaemon** [react-component/drawer#46]
I can see scrollbars in the examples of rc-drawer website, as well as my experiment with drawer.
I really want to get rid of the scrollbar at the bottom.

![drawer](https://i.imgur.com/OQufOSi.png)

**Comment by jljsj33** [comment]
~width: menu width + 1,,,~

https://codesandbox.io/s/ww0r05ry7  Demo no problem. Please provide your demo.

**Comment by demonoidaemon** [comment]
```
.drawer {
  .ant-menu-inline,
  .ant-menu-vertical {
    border-right: none;
  }
```
Yes your example worked fine.
So I found out that I followed the index.less file inside drawer/examples/assets/, it's these lines causing my troubles.
Thanks.
