### ISSUE TITLE
        window.addEventListener('test', null, Object.defineProperty({}, 'passive', {

### ISSUE THREAD

**Issue by kalsolio** [react-component/drawer#49]
> Cannot read property 'name' of null
> 
>             (fn as any) as SentryWrappedFunction,
>             {
>               mechanism: {
>                 data: {
>                   function: 'addEventListener',
>                   handler: ((fn as any) as SentryWrappedFunction).name || '<anonymous>',
>                   target,
>                 },
>                 handled: true,
>                 type: 'instrument',
>               },

**Comment by jljsj33** [comment]
能提供重现步骤和实现环境？？？？？

**Comment by kalsolio** [comment]
Sentry fixed
