### ISSUE TITLE
Latest version 1.7.7 get stuck due to typo error

### ISSUE THREAD

**Issue by hoantran-it** [react-component/drawer#58]
I face up this error when the component auto update minor verion:
**'transitionStr' is not exported from './utils'.**

I think problem is typo mismatch **trnasitionStr** and **transitionStr**. Please help to take a look. Thanks!

**Comment by jljsj33** [comment]
There are no errors, try again. `rm -rf node_modules & npm install`

**Comment by jljsj33** [comment]
https://react-component.github.io/drawer/examples/simple.html, is normal.

**Comment by hoantran-it** [comment]
Auto upgrade of npm did not work correctly, try to remove and reinstall will help. Thank you @jljsj33!
