### ISSUE TITLE
'./utils' does not contain an export named 'transitionStr'.

### ISSUE THREAD

**Issue by rajeevao** [react-component/drawer#61]
Hi,

I get the following error after updating to the latest version. 

./node_modules/rc-drawer/es/Drawer.js
372:16-29 './utils' does not contain an export named 'transitionStr'.

The compile error  can be fixed by removing  "transitionStr" from the import statement in Drawer.js.
import { dataToArray, transitionEnd, transitionStr, addEventListener, removeEventListener, transformArguments, isNumeric } from './utils';

Could you please check this?

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/issues/58
