### ISSUE TITLE
当drawer中的内容超过整屏的高度，不能向下拉

### ISSUE THREAD

**Issue by johanazhu** [react-component/drawer#84]
现在有个需求，drawer中有大量的数据，而这些数据会超过整个屏幕，因为禁止了touchmove，所以整个body不能下拉，包括drawer中，所以能解决下吗

**Comment by jljsj33** [comment]
drawer 里没有禁止啊，我这边测了可以下拉。。。

**Comment by johanazhu** [comment]
在iphone上是ok的，但是在华为手机上划不动

**Comment by jljsj33** [comment]
好的，，记录一下，，我找台华为的看看。。。

**Comment by jljsj33** [comment]
安卓下不支持 scrollTo, 不锁定滚动了。。

**Comment by afc163** [comment]
不一定所有 Android 都是这个行为吧。

**Comment by jljsj33** [comment]
uc 11.8 以下的不支持 scrollTo，12开始用 Chromium 内核了被直接忽略 preventDefault() 了。。

Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by johanazhu** [comment]
我刚刚试了试，发现一个问题，项目H5是镶嵌在app中，当我点开rc-drawer组件后（内容溢出情况下），还是不懂不了，当我退出这个页面，重新进入的话，就可以滑动，这是啥原因

**Comment by jljsj33** [comment]
重新安装 rc-drawer ，，再清除下缓存,或在 js 后面加个参数，，安卓机器调试我以前都是 js 后面加 ?xxx

**Comment by jljsj33** [comment]
好像 scrollTop 可以用，，我再看看。。。

**Comment by johanazhu** [comment]
项目是镶嵌在app中的H5，当内容超出drawer高度时，华为手机不能下滑，下滑出现抖动现象
