### ISSUE TITLE
Error with Sentry package 

### ISSUE THREAD

**Issue by 3dw1np** [react-component/drawer#85]
By adding the sentry lib with the following guide:
https://docs.sentry.io/platforms/javascript/react/

I have an error display on the browser console with the Drawer component: "rc-drawer": "^1.7.8"

```
breadcrumbs.js:81 Uncaught TypeError: Cannot read property 'handleEvent' of null
    at breadcrumbs.js:81
    at ProxyComponent.componentDidMount (Drawer.js:49)
```

```
Drawer.js
window.addEventListener('test', null, Object.defineProperty({}, 'passive', {
          get: function get() {
            passiveSupported = true;
            return null;
          }
        }));
```

**Comment by 3dw1np** [comment]
Seems related to #49 or maybe not ...

**Comment by jljsj33** [comment]
#49 `Sentry` fixed, please update `Sentry`.

https://github.com/getsentry/sentry-javascript/pull/2028/files#diff-d18e7ad9c3133436f6c3172210db6597R151
