### ISSUE TITLE
Bottom scroll is shown

### ISSUE THREAD

**Issue by apaniuk** [react-component/drawer#97]
Bottom scroll is shown while drawer is closing for a few seconds;

**Comment by apaniuk** [comment]
When drawer has placement 'left' side

**Comment by apaniuk** [comment]
Please check your demo https://react-component.github.io/drawer/examples/placement.html
Switch to right placement and look at left side of browser it starts opening there
![image](https://user-images.githubusercontent.com/22519385/58131696-ffe0c480-7c27-11e9-9802-d15ab8869ed1.png)

**Comment by jljsj33** [comment]
Menu border 1px problem, you can add DIV in the outer layer and set the width or set the `.drawer-content`
```
<Drawer>
  <div style={ width: 'calc(100% - 1px)' }>
    <Menu />
  </div>
</Drawer>
```

**Comment by apaniuk** [comment]
Unfortunately you didn't understand me. 
When you set placement right and there is scroll in the page and opening the drawer it starts opening in leftside and after that it is opening in right side as it must be

**Comment by apaniuk** [comment]
![image](https://user-images.githubusercontent.com/22519385/58154115-8376d180-7c79-11e9-9ba2-abfd11172a81.png)
![image](https://user-images.githubusercontent.com/22519385/58154132-8b367600-7c79-11e9-9f9a-45f3eb28ac35.png)

**Comment by jljsj33** [comment]
https://github.com/react-component/drawer/commit/f68b83a7f73ecc1c0793be013d1ba7e66a7e96b1#diff-0e1130f84eefdbec26836cf3da534eb4L72

This may be the problem, ~but there is no problem under os~.

**Comment by jljsj33** [comment]
v1.9.5
